### ISSUE TITLE
NullPointerException at fr.inria.zvtm.svg.SVGReader.load

### ISSUE THREAD

**Issue by jhavlin** [sharwell/zgrnbviewer#2]
Hello,

this exception has been reported to NetBeans Bugzilla.

Stacktrace:

```
java.lang.NullPointerException
   at fr.inria.zvtm.svg.SVGReader.load(SVGReader.java:1802)
   at net.claribole.zgrviewer.DOTManager.displaySVG(DOTManager.java:309)
   at net.claribole.zgrviewer.DOTManager.callGraphViz(DOTManager.java:96)
   at net.claribole.zgrviewer.DOTManager.load(DOTManager.java:58)
   at net.claribole.zgrviewer.GVLoader.loadFile(GVLoader.java:101)
   at org.tvl.netbeans.zgrviewer.GraphVizVisualElement.reloadDocument(GraphVizVisualElement.java:179)
```

See https://netbeans.org/bugzilla/show_bug.cgi?id=254533.

Please evaluate this bug. Thank you.

**Comment by tim-hoffman** [comment]
I experienced the same exception. In my case, the full file path was longer than the 260 character limit on Windows. Shortening the filename or the name of an intermediate directory was enough to get it below the character limit and it loaded without exception. One possible solution could be to prefix the path with `\\?\` which allows longer paths on Windows (up to 32K characters I believe).
